#!/bin/bash
p=/var/www/html/interWebs/"$1"
if [ -f "$p" ] ; then
	cat "$p" | sed 's/error_log\((.*\),.*\(;\)/$page=new pageCtl(\1)\2/'
cp "$p" "$p".bak
read -p "Are you sure?[yes]: " x
[ $x == "yes" ] && cat "$p" | sed 's/$this->error..=\(.*\)\(;\)/error_log(\1,3,"\/var\/www\/html\/interWebs\/errorlog\/error")\2/' > "$p".cool && echo "All done Sir!" && exit 0
else
	echo "no file here!"
fi
	echo "File has not been edited"
